const STORAGE_KEY='trip_itinerary_v3';const COUNTRY_KEY='selected_country_v3';
function getData(){const s=localStorage.getItem(STORAGE_KEY);if(s){try{return JSON.parse(s)}catch(e){}}localStorage.setItem(STORAGE_KEY,JSON.stringify(window.ITINERARY_DATA));return window.ITINERARY_DATA}
function saveData(d){localStorage.setItem(STORAGE_KEY,JSON.stringify(d))}
function qs(id){return document.getElementById(id)}
function sanitizeQuery(s){return (s||'').toString().trim()}
function unique(a){return Array.from(new Set(a))}
function buildMapsUrl(q){const x=encodeURIComponent((q||'').toString().trim());return `https://www.google.com/maps/search/?api=1&query=${x}`}
function parseHash(){const h=(location.hash||'').replace(/^#/,'');const p=new URLSearchParams(h);const d=p.get('day');return{day:d?Number(d):null}}
function setHashDay(i){const p=new URLSearchParams();p.set('day',String(i));location.hash=p.toString()}
function show(el){el.classList.remove('hidden')}
function hide(el){el.classList.add('hidden')}
function colorForCountry(c){c=(c||'').toString();if(c.includes('תאילנד'))return['#22c55e','#2a4bff'];if(c.includes('יפן'))return['#fb7185','#7c3aed'];if(c.includes('וייטנאם'))return['#f59e0b','#ef4444'];if(c.includes('קמבודיה'))return['#38bdf8','#a78bfa'];if(c.includes('סינגפור'))return['#60a5fa','#34d399'];if(c.includes('מלזיה'))return['#f472b6','#22c55e'];return['#2a4bff','#7c3aed']}
function iconForType(t){t=(t||'').toString();if(t.includes('אוכל'))return'🍽️';if(t.includes('לינה'))return'🏨';if(t.includes('מעבר'))return'🚗';return'🌴'}
function svgBanner(title,country){const[a,b]=colorForCountry(country);const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="520" viewBox="0 0 1200 520"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${a}" stop-opacity="0.85"/><stop offset="1" stop-color="${b}" stop-opacity="0.75"/></linearGradient><radialGradient id="r" cx="30%" cy="15%" r="70%"><stop offset="0" stop-color="white" stop-opacity="0.22"/><stop offset="1" stop-color="white" stop-opacity="0"/></radialGradient><filter id="blur" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="24"/></filter></defs><rect width="1200" height="520" fill="url(#g)"/><circle cx="260" cy="140" r="210" fill="url(#r)"/><circle cx="940" cy="120" r="180" fill="white" opacity="0.12"/><circle cx="920" cy="380" r="260" fill="white" opacity="0.06" filter="url(#blur)"/><path d="M0,410 C240,330 360,520 600,440 C840,360 960,520 1200,420 L1200,520 L0,520 Z" fill="black" opacity="0.18"/><path d="M0,360 C240,280 360,460 600,390 C840,320 960,460 1200,370" fill="white" opacity="0.10"/></svg>`;return`data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`}
function setHeroBackground(country,loc){const hero=qs('dayHero');hero.style.backgroundImage=`url("${svgBanner(loc||'יום טיול',country)}")`;hero.style.backgroundSize='cover';hero.style.backgroundPosition='center'}
function renderCountryChips(data,selected,onSelect){const countries=unique(data.days.map(d=>d.country||'לא מסווג'));const chips=[{name:'כל המדינות',value:''},...countries.map(c=>({name:c,value:c}))];const wrap=qs('countryChips');wrap.innerHTML=chips.map(c=>{const active=(c.value===selected)||(c.value===''&&!selected);return`<button class="chip ${active?'active':''}" data-country="${c.value}">${c.name}</button>`}).join('');wrap.querySelectorAll('[data-country]').forEach(b=>b.addEventListener('click',()=>onSelect(b.getAttribute('data-country')||'')))}
function renderHome(data){qs('tripTitle').textContent=data.title||'';const list=qs('daysList');const qEl=qs('q');const dateEl=qs('dateFilter');let selected=localStorage.getItem(COUNTRY_KEY)||'';const uniqDates=unique(data.days.map(d=>d.date));dateEl.innerHTML='<option value="">כל התאריכים</option>'+uniqDates.map(d=>`<option value="${d}">${d}</option>`).join('');
function matchDay(day,q,date,country){if(country&&(day.country||'לא מסווג')!==country)return false;if(date&&day.date!==date)return false;if(!q)return true;const t=q.toLowerCase();const hay=[day.date,day.location,day.lodging,day.country,...(day.transfers||[]),...((day.places||[]).map(p=>p.name))].join(' ').toLowerCase();return hay.includes(t)}
function setCountry(c){selected=c;localStorage.setItem(COUNTRY_KEY,selected);renderCountryChips(data,selected,setCountry);draw()}
function dayCard(d,idx){const loc=d.location||'לא צוין';const lod=d.lodging||'לא צוין';const country=d.country||'לא מסווג';const placesCount=(d.places||[]).length;const banner=svgBanner(loc,country);return`<div class="dayCard"><div class="dayCard__banner" style="background-image:url('${banner}'); background-size:cover; background-position:center;"></div><div class="dayCard__content"><div class="dayCard__row"><div><div class="dayCard__date">${d.date||''}</div><div class="dayCard__loc">${loc}</div><div class="dayCard__meta">מדינה: ${country} | לינה: ${lod}</div></div><div class="badge">${placesCount} מקומות</div></div><div class="actions"><button class="pill pill--primary" data-open-day="${idx}">פתח יום</button><a class="pill" href="${buildMapsUrl(loc)}" target="_blank" rel="noopener">מפות</a></div></div></div>`}
function draw(){const q=sanitizeQuery(qEl.value);const date=dateEl.value||'';const filtered=data.days.map((d,idx)=>({d,idx})).filter(x=>matchDay(x.d,q,date,selected));list.innerHTML=filtered.map(({d,idx})=>dayCard(d,idx)).join('');list.querySelectorAll('[data-open-day]').forEach(btn=>btn.addEventListener('click',()=>setHashDay(Number(btn.getAttribute('data-open-day')))))}
renderCountryChips(data,selected,setCountry);qEl.oninput=draw;dateEl.onchange=draw;draw()}
function renderDay(data,idx){const day=data.days[idx];if(!day)return;qs('dayDate').textContent=day.date||'';const meta=[];if(day.country)meta.push(`מדינה: ${day.country}`);if(day.location)meta.push(`מיקום: ${day.location}`);if(day.places?.length)meta.push(`מקומות: ${day.places.length}`);qs('dayMeta').textContent=meta.join(' | ');setHeroBackground(day.country,day.location);qs('dayLodging').textContent=day.lodging||'לא צוין';
const transfersUl=qs('dayTransfers');const transfers=day.transfers||[];transfersUl.innerHTML=transfers.length?transfers.map(t=>`<li>${t}</li>`).join(''):'<li>לא צוינו מעברים</li>';
const wrap=qs('placesList');const places=day.places||[];wrap.innerHTML=places.length?places.map(p=>{const type=p.type||'מקום';const icon=iconForType(type);const[a,b]=colorForCountry(day.country);const thumbSvg=`<svg xmlns="http://www.w3.org/2000/svg" width="240" height="360" viewBox="0 0 240 360"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${a}" stop-opacity="0.85"/><stop offset="1" stop-color="${b}" stop-opacity="0.75"/></linearGradient></defs><rect width="240" height="360" rx="28" fill="url(#g)"/><circle cx="70" cy="90" r="56" fill="white" opacity="0.18"/><circle cx="170" cy="160" r="76" fill="white" opacity="0.10"/><path d="M0,260 C60,230 80,320 140,280 C190,248 210,320 240,290 L240,360 L0,360 Z" fill="black" opacity="0.18"/></svg>`;const thumb=`data:image/svg+xml;charset=utf-8,${encodeURIComponent(thumbSvg)}`;const mapsUrl=buildMapsUrl(p.name||day.location||'');return`<div class="place"><div class="thumb" style="background-image:url('${thumb}'); background-size:cover; background-position:center;"><div class="thumb__icon">${icon}</div><div class="thumb__label">${(p.name||'').toString()}</div></div><div class="place__body"><div class="place__name">${(p.name||'').toString()}</div><div class="place__type">${type}</div><div class="place__actions"><a class="small" href="${mapsUrl}" target="_blank" rel="noopener">פתח במפות</a><button class="small" data-copy="${(p.name||'').toString()}">העתק שם</button></div></div></div>`}).join(''):'<div class="text">לא צוינו מקומות ליום זה</div>';
wrap.querySelectorAll('[data-copy]').forEach(btn=>btn.addEventListener('click',async()=>{const t=btn.getAttribute('data-copy')||'';try{await navigator.clipboard.writeText(t)}catch(e){}btn.textContent='הועתק';setTimeout(()=>btn.textContent='העתק שם',900)}))}
function showHome(){show(qs('viewHome'));hide(qs('viewDay'))}
function showDay(){hide(qs('viewHome'));show(qs('viewDay'))}
function wireActions(){qs('btnHome').addEventListener('click',()=>{location.hash=''});qs('btnBack').addEventListener('click',()=>{location.hash=''});qs('btnCopyLink').addEventListener('click',async()=>{const url=location.href;try{await navigator.clipboard.writeText(url)}catch(e){}qs('btnCopyLink').textContent='הועתק';setTimeout(()=>qs('btnCopyLink').textContent='העתק קישור',900)});
qs('btnExport').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(getData(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='itinerary-backup.json';a.click();URL.revokeObjectURL(a.href)});
qs('btnImport').addEventListener('click',()=>qs('importFile').click());qs('importFile').addEventListener('change',async(e)=>{const f=e.target.files&&e.target.files[0];if(!f)return;const text=await f.text();try{const j=JSON.parse(text);if(!j||!Array.isArray(j.days))throw new Error('bad');saveData(j);location.reload()}catch(err){alert('קובץ לא תקין')}});
qs('tabHome').addEventListener('click',()=>{location.hash='';window.scrollTo({top:0,behavior:'smooth'})});qs('tabTop').addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}))}
function main(){const data=getData();qs('tripTitle').textContent=data.title||'';wireActions();
function route(){const{day}=parseHash();if(day!==null&&!Number.isNaN(day)&&day>=0&&day<data.days.length){showDay();renderDay(data,day)}else{showHome();renderHome(data)}}
window.addEventListener('hashchange',route);route()}
main();
